import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import React from "react";
const inter = Inter({ subsets: ["latin"] });
import MainLayout from "@/components/mainLayout";
import getInfo from "@/action/getInfo";
import { AppWrapper } from "@/context/infoLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: `/next.svg`,
  },
};

export default function RootLayout({
  banner,
  product,
  popular,
}: Readonly<{
  banner: React.ReactNode;
  product: React.ReactNode;
  popular: React.ReactNode;
}>) {
  const infoLayout = React.use(getInfo());
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWrapper>
          <MainLayout data = {infoLayout.data}>
              {banner}
              {popular}
              {product} 
          </MainLayout>
        </AppWrapper>
      </body>
    </html>
  );
}
