import "../../globals.css";
import React from "react";
import MainLayout from "@/components/mainLayout";
import getInfo from "@/action/getInfo";
import getFooter from "@/actions/getFooter";
import { AppWrapper } from "@/context/infoLayout";
import { ProductWrapper } from "@/context/productLayout";
import TransactionLayout from "@/components/transactionLayout";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  description,
  form,
}: Readonly<{
  children: React.ReactNode;
  description: React.ReactNode;
  form: React.ReactNode;
}>) {
  const infoLayout = React.use(getInfo());
  const dataFooter = React.use(getFooter());

  return (
    <html lang="en">
      <body>
        <AppWrapper>
          <MainLayout data = {infoLayout.data} dataFooter = {dataFooter.data}>
              {children}
              <ProductWrapper>
                <TransactionLayout description = {description} form ={form} />
              </ProductWrapper>
          </MainLayout>
        </AppWrapper>
      </body>
    </html>
  )
}
